name: nexus-wallet

services:
  db:
    image: postgres:15-alpine
    container_name: nexus-postgres-dev
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nexus_wallet

  redis:
    image: redis:7-alpine
    container_name: nexus-redis-dev
    restart: always
    env_file:
      - ../../.env
    ports:
      - "6379:6379"
    volumes:
      - redisdata_dev:/data

  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    container_name: nexus-backend-dev
    restart: always
    env_file:
      - ../../.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/nexus_wallet?schema=public
      - REDIS_URL=redis://redis:6379
      - HOST=0.0.0.0
      - PORT=8002
    ports:
      - "8002:8002"
    depends_on:
      - db
      - redis

volumes:
  pgdata_dev:
  redisdata_dev:
