name: nexus-wallet

services:
  db:
    image: postgres:15-alpine
    container_name: nexus-postgres-prod
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  redis:
    image: redis:7-alpine
    container_name: nexus-redis-prod
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata_prod:/data

  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    container_name: nexus-backend-prod
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - REDIS_URL=redis://redis:6379
      - HOST=0.0.0.0
      - PORT=8002
      - JWT_ACCESS_SECRET
      - JWT_REFRESH_SECRET
      - ACCESS_TOKEN_TTL
      - REFRESH_TOKEN_TTL_DAYS
      - COINGECKO_API_KEY
      - COINGECKO_BASE_URL
      - SWAP_FEE_PERCENT
      - WEBHOOK_SECRET
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata_prod:
  redisdata_prod:
